import { Component, OnInit, TemplateRef } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Title, Meta } from '@angular/platform-browser';
import { NgForm } from '@angular/forms'
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-prodmarket',
  templateUrl: './prodmarket.component.html',
  styleUrls: ['./prodmarket.component.css']
})
export class ProdmarketComponent implements OnInit {

  enquiryModal:any = FormGroup;
  submitted = false;
  arr: any[] = [];

  selectedTab: any = '1';

  isShown: boolean = false;

  faq_array: any[] = [
    {
      title: 'What is Product Marketing?',
      sub_text: '',
      message_list: ['Product marketing comprises the plans and strategies to generate demand and use of your product. It defines brand positioning, product messaging and its value proposition. It also involves education of internal and external stakeholders about the product.'],

    },
    {
      title: 'Why is Product Marketing important?',
      sub_text: '',
      message_list: ['Product marketing is very important for all businesses, especially for startups. All the efforts that go into product development go wasted if it does not reach the right audience. There will be no market awareness or interest in your product without proper marketing. '],

    },
    {
      title: 'What are the benefits of Product Marketing?',
      sub_text: 'Product marketing helps customers get answers to questions such as:',
      message_list: ['What is the product?',
        'What do consumers get out of the product?',
        'Why is the product better than its competition?',
        'What is the price of the product?',
        'How can one go about purchasing the product?'],

      last_text: 'Product marketing helps generate demand from prospective customers and up-sell to existing ones.'

    },
    {
      title: 'What are the tasks in Product marketing?',
      sub_text: 'Although the product marketing tasks vary from one company to another, given below are the most common tasks in product marketing:',
      message_list: ['Creation of product positioning and messaging',
        'Organization of product launches',
        'Research of market, competitors, and customers',
        'Generation of product content across all digital platforms',
        'Revamp the product website',
        'Analysis and report of product performance'],

    },
    {
      title: 'What are the metrics to measure product marketing?',
      sub_text: 'Product marketing can be measured based on the factors given below:',
      message_list: ['Overall revenue generated by product sales',
        'Analyse the product launch metrics and its impact on demand and sales',
        'Product usage',
        'Customer satisfaction and happiness converting to retention'],

    },
    {
      title: 'How can product marketing be done for a new product?',
      sub_text: 'Given below are some of the ways in which product marketing can be done for new products:',
      message_list: ['Offer customers a preview or demo',
        'Give introductory offers and discounts',
        'Advertise on Google business listings',
        'Run ads and contests on social media platforms',
        'Send out emails and newsletters to prospects',
      ],
    }
  ]

  constructor(meta: Meta, title: Title,private modalService: BsModalService, private httpClient: HttpClient, private router: Router, private formBuilder: FormBuilder) {
    title.setTitle('Product Markting');

    meta.addTags([
      {
        name: 'description',
        content: 'Product Markting'
      },
      {
        name: 'keywords',
        content: 'Product Markting'
      },
      {
        name: 'og:type',
        content: 'article'
      },
      {
        name: 'og:title',
        content: 'Product Markting'
      },
      {
        name: 'og:description',
        content: 'Product Markting'
      },
      {
        name: 'og:url',
        content: 'https://brandstory.in/account-based-marketing/'
      },
      {
        name: 'og:site_name',
        content: 'Product Markting'
      },
      {
        name: 'twitter:card',
        content: 'Product Markting'
      },
      {
        name: 'twitter:description',
        content: 'Product Markting'
      },
      {
        name: 'twitter:title',
        content: 'Product Markting'
      }
    ]);
  }

  get fenquiryModal() { return this.enquiryModal.controls; }


  scrollToElement($element: any): void {
    console.log($element);
    $element.scrollIntoView({ behavior: "smooth", block: "start", inline: "nearest" });
  }
  modalRef: any = BsModalRef;

  openModal(template: TemplateRef<any>) {
    this.modalRef = this.modalService.show(template);
  }

  ngOnInit(): void {

    this.enquiryModal = this.formBuilder.group({
      fName: ['', [Validators.required, Validators.pattern('[a-zA-Z ]*'), Validators.minLength(3)]],
      fEmail: ['', [Validators.required, Validators.email, Validators.pattern('^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$')]],
      fPhone: ['', [Validators.required, Validators.pattern('^((\\+91-?)|0)?[0-9]{10,11}$')]],
      organisation: ['', [Validators.required]],
      fService: ['', Validators.required],
      fMessage: ['', Validators.required]
    });

    this.faq_click(0);


  }


  onSubmitEnquiryModal() {
    this.submitted = true;
    this.arr = this.enquiryModal.value;

    if (this.enquiryModal.invalid) {
      return;
    }

    const formName = this.enquiryModal.value.fName;
    const formEmail = this.enquiryModal.value.fEmail;
    const formPhone = this.enquiryModal.value.fPhone;
    const organisation = this.enquiryModal.value.organisation;
    const formService = this.enquiryModal.value.fService;
    const formMessage = this.enquiryModal.value.fMessage;


    //this.httpClient.post('https://brandstory.in/assets/thank-you-enquiry-modal.php',
    this.httpClient.post('https://brandstory.in/assets/thank-you-enquiry-home.php',
      {
        name: formName,
        email: formEmail,
        phone: formPhone,
        company: organisation,
        service: formService,
        message: formMessage,
        page: "brandstory.in/product-marketing"

      })
      .subscribe(
        (data: any) => {
          this.modalRef.hide();
          // this.router.navigate(['thank-you']);
          window.location.href = "https://brandstory.in/thank-you"
          console.log(data);
        }
      )

    this.httpClient.post('https://brandstory.in/assets/customer_mail_2021.php',
      {
        name: formName,
        email: formEmail,
        phone: formPhone,
        company: organisation,
        service: formService,
        message: formMessage,
        page: "brandstory.in/product-marketing"
      })
      .subscribe(
        (data: any) => {
          //this.modalRef.hide();
          // this.router.navigate(['thank-you']);
          //  window.location.href = "https://brandstory.in/thank-you"
          // console.log(data);
        }
      )

  }


  faq_click(index: any) {
    // debugger;

    // if (type == this.selectedTab)
    //   this.selectedTab = '';
    // else
    //   this.selectedTab = type;


    // this.faq_array.forEach(element => {
    //   element.checked = false;
    // });

    if (this.faq_array[index].checked)
      this.faq_array[index].checked = false;
    else {
      this.faq_array.forEach(element => {
        element.checked = false;
      });

      this.faq_array[index].checked = true;

    }

  }

}
